---
- name: Install python packages via aptitude
  sudo: true
  apt:
    name={{ item }}
    state=installed
  with_items:
    - zlib1g-dev
    - libreadline-dev
    - libbz2-dev
    - libsqlite3-dev
    - libssl-dev
    - python-pip
    - python-matplotlib
- name: Install some python packages via pip (which aren't available via aptitude)
  pip:
    name={{ item }}
  with_items:
    - jupyter
