---
- name: Install luigi via pip
  become: yes
  pip: name=luigi version=2.1.0 # Has to be 2.1.0 to not give warnings about non-string parameters
- name: Install sciluigi via pip
  become: yes
  pip:
    name={{ item }}
  with_items:
    - tornado
    - sciluigi
